import 'package:document_studio/features/compose/compose_model.dart';

/// One insertable piece of syntax, with its help text.
///
/// In [insert], `$|` marks where the cursor lands and `$SEL` is replaced by
/// the selected text (so "Bold" wraps a selection).
class ComposeSnippet {
  const ComposeSnippet(
    this.category,
    this.label,
    this.insert,
    this.help, {
    this.trigger,
  });

  final String category;
  final String label;
  final String insert;
  final String help;

  /// What the user types for autocomplete (`\section`, `<table`, `##`).
  final String? trigger;

  String get preview =>
      insert.replaceAll(r'$|', '').replaceAll(r'$SEL', 'text');
}

List<ComposeSnippet> snippetsFor(ComposeLanguage l) => switch (l) {
  ComposeLanguage.markdown => _markdown,
  ComposeLanguage.html => _html,
  ComposeLanguage.latex => _latex,
};

/// Shared TeX maths (Markdown `$…$`, HTML `\(…\)`, LaTeX).
const _math = <ComposeSnippet>[
  ComposeSnippet(
    'Maths',
    'Fraction',
    r'\frac{$|}{}',
    'a over b',
    trigger: r'\frac',
  ),
  ComposeSnippet(
    'Maths',
    'Square root',
    r'\sqrt{$|}',
    'Root; \\sqrt[n]{x} for nth root',
    trigger: r'\sqrt',
  ),
  ComposeSnippet(
    'Maths',
    'Power / index',
    r'x^{$|}',
    'Superscript ^{…}, subscript _{…}',
  ),
  ComposeSnippet(
    'Maths',
    'Sum',
    r'\sum_{i=1}^{n} $|',
    'Summation with limits',
    trigger: r'\sum',
  ),
  ComposeSnippet(
    'Maths',
    'Product',
    r'\prod_{i=1}^{n} $|',
    'Product with limits',
    trigger: r'\prod',
  ),
  ComposeSnippet(
    'Maths',
    'Integral',
    r'\int_{a}^{b} $| \, dx',
    'Definite integral; \\iint, \\oint',
    trigger: r'\int',
  ),
  ComposeSnippet(
    'Maths',
    'Limit',
    r'\lim_{x \to $|}',
    'Limit',
    trigger: r'\lim',
  ),
  ComposeSnippet(
    'Maths',
    'Derivative',
    r'\frac{d$|}{dx}',
    'd/dx; \\partial for partial',
    trigger: r'\partial',
  ),
  ComposeSnippet(
    'Maths',
    'Matrix',
    r'\begin{pmatrix} a & b \\ c & d \end{pmatrix}',
    'pmatrix ( ), bmatrix [ ], vmatrix | |',
    trigger: r'\begin{pmatrix}',
  ),
  ComposeSnippet(
    'Maths',
    'Cases',
    r'f(x) = \begin{cases} $| & x \ge 0 \\ 0 & x < 0 \end{cases}',
    'Piecewise definition',
    trigger: r'\begin{cases}',
  ),
  ComposeSnippet(
    'Maths',
    'Vector / hat / bar',
    r'\vec{$|}',
    '\\vec \\hat \\bar \\tilde \\dot \\overline',
    trigger: r'\vec',
  ),
  ComposeSnippet(
    'Maths',
    'Bold / blackboard',
    r'\mathbb{R}',
    '\\mathbb{R} \\mathbf{v} \\mathcal{L} \\mathrm{d}',
    trigger: r'\mathbb',
  ),
  ComposeSnippet(
    'Maths',
    'Text inside maths',
    r'\text{$|}',
    'Upright words in a formula',
    trigger: r'\text',
  ),
  ComposeSnippet(
    'Maths',
    'Brackets that grow',
    r'\left( $| \right)',
    '\\left( \\right) \\left[ \\right] \\left\\{ \\right\\}',
    trigger: r'\left',
  ),
  ComposeSnippet(
    'Maths',
    'Greek letters',
    r'\alpha \beta \gamma \delta \epsilon \theta \lambda \mu \pi \sigma \phi \omega',
    'Capitals: \\Gamma \\Delta \\Theta \\Lambda \\Pi \\Sigma \\Phi \\Omega',
    trigger: r'\alpha',
  ),
  ComposeSnippet(
    'Maths',
    'Relations',
    r'\le \ge \ne \approx \equiv \sim \propto \in \notin \subset \subseteq',
    'Comparison and set relations',
    trigger: r'\le',
  ),
  ComposeSnippet(
    'Maths',
    'Operators',
    r'\times \cdot \div \pm \mp \cup \cap \setminus \nabla \infty',
    'Binary operators and symbols',
    trigger: r'\times',
  ),
  ComposeSnippet(
    'Maths',
    'Arrows',
    r'\to \Rightarrow \Leftrightarrow \mapsto \leftarrow \uparrow',
    'Arrows; \\implies \\iff',
    trigger: r'\Rightarrow',
  ),
  ComposeSnippet(
    'Maths',
    'Logic / sets',
    r'\forall \exists \neg \land \lor \emptyset \mathbb{N}',
    'Quantifiers and sets',
    trigger: r'\forall',
  ),
  ComposeSnippet(
    'Maths',
    'Dots',
    r'\ldots \cdots \vdots \ddots',
    'Ellipses',
    trigger: r'\cdots',
  ),
  ComposeSnippet(
    'Maths',
    'Functions',
    r'\sin \cos \tan \log \ln \exp \max \min \det',
    'Upright function names',
    trigger: r'\sin',
  ),
  ComposeSnippet(
    'Maths',
    'Binomial',
    r'\binom{n}{k}',
    'n choose k',
    trigger: r'\binom',
  ),
  ComposeSnippet(
    'Maths',
    'Overbrace / underbrace',
    r'\underbrace{$|}_{\text{note}}',
    '\\overbrace{…}^{…}',
    trigger: r'\underbrace',
  ),
  ComposeSnippet(
    'Maths',
    'Spacing',
    r'a \, b \; c \quad d \qquad e',
    'Thin, medium, quad, double quad',
    trigger: r'\quad',
  ),
];

const _markdown = <ComposeSnippet>[
  ComposeSnippet(
    'Structure',
    'Heading 1',
    '# \$|',
    'Largest heading (# to ###### for levels 1–6)',
    trigger: '#',
  ),
  ComposeSnippet(
    'Structure',
    'Heading 2',
    '## \$|',
    'Section heading',
    trigger: '##',
  ),
  ComposeSnippet(
    'Structure',
    'Heading 3',
    '### \$|',
    'Sub-section heading',
    trigger: '###',
  ),
  ComposeSnippet(
    'Structure',
    'Horizontal rule',
    '\n---\n',
    'Three dashes on their own line',
    trigger: '---',
  ),
  ComposeSnippet(
    'Structure',
    'Page break',
    '\n<div style="page-break-after: always"></div>\n',
    'Start a new page (also \\newpage)',
    trigger: 'newpage',
  ),
  ComposeSnippet(
    'Text',
    'Bold',
    '**\$SEL\$|**',
    'Strong emphasis — **text** or __text__',
    trigger: '**',
  ),
  ComposeSnippet(
    'Text',
    'Italic',
    '*\$SEL\$|*',
    'Emphasis — *text* or _text_',
    trigger: '*',
  ),
  ComposeSnippet(
    'Text',
    'Bold italic',
    '***\$SEL\$|***',
    'Both',
    trigger: '***',
  ),
  ComposeSnippet(
    'Text',
    'Strikethrough',
    '~~\$SEL\$|~~',
    'Crossed-out text',
    trigger: '~~',
  ),
  ComposeSnippet(
    'Text',
    'Inline code',
    '`\$SEL\$|`',
    'Monospace code in a sentence',
    trigger: '`',
  ),
  ComposeSnippet(
    'Text',
    'Line break',
    '  \n',
    'End a line with two spaces (or use <br>)',
  ),
  ComposeSnippet(
    'Text',
    'Escape a symbol',
    r'\*',
    r'Backslash shows the character literally: \* \_ \# \$',
  ),
  ComposeSnippet(
    'Lists',
    'Bulleted list',
    '- \$|\n- \n- ',
    'Start lines with -, * or +',
    trigger: '-',
  ),
  ComposeSnippet(
    'Lists',
    'Numbered list',
    '1. \$|\n2. \n3. ',
    'Start lines with 1. 2. 3.',
    trigger: '1.',
  ),
  ComposeSnippet(
    'Lists',
    'Nested list',
    '- Item\n  - Sub-item \$|\n',
    'Indent two spaces to nest',
  ),
  ComposeSnippet(
    'Lists',
    'Task list',
    '- [ ] \$|\n- [x] Done',
    'Check boxes',
    trigger: '- [',
  ),
  ComposeSnippet(
    'Blocks',
    'Quote',
    '> \$SEL\$|',
    'Block quotation',
    trigger: '>',
  ),
  ComposeSnippet(
    'Blocks',
    'Code block',
    '```\n\$SEL\$|\n```',
    'Fenced code; add a language after ``` (```python)',
    trigger: '```',
  ),
  ComposeSnippet(
    'Blocks',
    'Table',
    '| Column | Column |\n| :----- | -----: |\n| \$|     |        |',
    'Pipes split cells; :--- left, :--: centre, ---: right',
    trigger: '|',
  ),
  ComposeSnippet(
    'Links & media',
    'Link',
    '[\$SEL\$|](https://)',
    '[text](url)',
    trigger: '[',
  ),
  ComposeSnippet(
    'Links & media',
    'Image',
    '![caption](\$|image.png)',
    'Path relative to the opened file; data: URIs work too',
    trigger: '![',
  ),
  ComposeSnippet(
    'Maths',
    'Inline maths',
    r'$$|$',
    r'TeX between single dollars: $x^2$',
    trigger: r'$',
  ),
  ComposeSnippet(
    'Maths',
    'Display maths',
    '\$\$\n\$|\n\$\$',
    r'Centred formula between $$ … $$',
    trigger: r'$$',
  ),
  ComposeSnippet(
    'Text',
    'Subscript / superscript',
    'H<sub>2</sub>O, x<sup>2</sup>',
    'HTML tags work inside Markdown',
  ),
  ComposeSnippet(
    'Text',
    'Keyboard key',
    '<kbd>Ctrl</kbd> + <kbd>S</kbd>',
    'Shows keys',
  ),
  ComposeSnippet(
    'Blocks',
    'Centred text',
    '<div style="text-align:center">\n\n\$|\n\n</div>',
    'Centre any block',
  ),
  ComposeSnippet(
    'Blocks',
    'Coloured text',
    '<span style="color:#d32f2f">\$SEL\$|</span>',
    'Any CSS colour',
  ),
  ComposeSnippet(
    'Blocks',
    'Python code',
    '```python\n\$|\n```',
    'Fenced block with a language',
  ),
  ComposeSnippet(
    'Lists',
    'Term and description',
    '**Term**  \n\$|Description\n',
    'Bold term, line break, text',
  ),
  ..._math,
];

const _html = <ComposeSnippet>[
  ComposeSnippet(
    'Document',
    'Page skeleton',
    '<!doctype html>\n<html>\n<head>\n  <meta charset="utf-8">\n  <title>\$|Title</title>\n  <style>\n    @page { size: A4; }\n  </style>\n</head>\n<body>\n\n</body>\n</html>\n',
    'Complete page; @page size picks the paper (A4, Letter, A5)',
    trigger: '<html',
  ),
  ComposeSnippet(
    'Headings',
    'Heading 1',
    '<h1>\$SEL\$|</h1>',
    '<h1> … <h6>',
    trigger: '<h1',
  ),
  ComposeSnippet(
    'Headings',
    'Heading 2',
    '<h2>\$SEL\$|</h2>',
    'Section heading',
    trigger: '<h2',
  ),
  ComposeSnippet(
    'Headings',
    'Heading 3',
    '<h3>\$SEL\$|</h3>',
    'Sub-section heading',
    trigger: '<h3',
  ),
  ComposeSnippet(
    'Text',
    'Paragraph',
    '<p>\$SEL\$|</p>',
    'Block of text; style="text-align:center|right|justify"',
    trigger: '<p',
  ),
  ComposeSnippet(
    'Text',
    'Bold',
    '<b>\$SEL\$|</b>',
    '<b> or <strong>',
    trigger: '<b',
  ),
  ComposeSnippet(
    'Text',
    'Italic',
    '<i>\$SEL\$|</i>',
    '<i> or <em>',
    trigger: '<i',
  ),
  ComposeSnippet(
    'Text',
    'Underline',
    '<u>\$SEL\$|</u>',
    'Underlined text',
    trigger: '<u',
  ),
  ComposeSnippet(
    'Text',
    'Strikethrough',
    '<s>\$SEL\$|</s>',
    '<s> or <del>',
    trigger: '<s',
  ),
  ComposeSnippet(
    'Text',
    'Superscript / subscript',
    'x<sup>\$|2</sup> H<sub>2</sub>O',
    '<sup> and <sub>',
    trigger: '<sup',
  ),
  ComposeSnippet(
    'Text',
    'Inline code',
    '<code>\$SEL\$|</code>',
    'Monospace',
    trigger: '<code',
  ),
  ComposeSnippet(
    'Text',
    'Coloured / sized text',
    '<span style="color:#d32f2f; font-size:14pt; font-weight:bold">\$SEL\$|</span>',
    'style: color, font-size (pt, px, em, %), font-weight, font-style, text-decoration',
    trigger: '<span',
  ),
  ComposeSnippet(
    'Text',
    'Small / big',
    '<small>\$SEL\$|</small>',
    '<small> <big> <mark>',
    trigger: '<small',
  ),
  ComposeSnippet(
    'Text',
    'Line break',
    '<br>',
    'New line inside a paragraph',
    trigger: '<br',
  ),
  ComposeSnippet(
    'Blocks',
    'Section / div',
    '<div style="text-align:center">\n  \$|\n</div>',
    'Grouping block; also <section>, <article>, <header>, <footer>, <center>',
    trigger: '<div',
  ),
  ComposeSnippet(
    'Blocks',
    'Quote',
    '<blockquote>\$SEL\$|</blockquote>',
    'Indented quotation',
    trigger: '<blockquote',
  ),
  ComposeSnippet(
    'Blocks',
    'Preformatted code',
    '<pre>\$SEL\$|</pre>',
    'Keeps spaces and line breaks',
    trigger: '<pre',
  ),
  ComposeSnippet(
    'Blocks',
    'Horizontal rule',
    '<hr>',
    'Divider line',
    trigger: '<hr',
  ),
  ComposeSnippet(
    'Blocks',
    'Page break',
    '<div style="page-break-after: always"></div>',
    'Start a new page',
    trigger: 'page-break',
  ),
  ComposeSnippet(
    'Lists',
    'Bulleted list',
    '<ul>\n  <li>\$|</li>\n  <li></li>\n</ul>',
    '<ul> with <li> items',
    trigger: '<ul',
  ),
  ComposeSnippet(
    'Lists',
    'Numbered list',
    '<ol>\n  <li>\$|</li>\n  <li></li>\n</ol>',
    '<ol start="3"> to start elsewhere',
    trigger: '<ol',
  ),
  ComposeSnippet(
    'Lists',
    'Definition list',
    '<dl>\n  <dt>Term</dt>\n  <dd>\$|Meaning</dd>\n</dl>',
    'Terms and descriptions',
    trigger: '<dl',
  ),
  ComposeSnippet(
    'Tables',
    'Table',
    '<table>\n  <caption>\$|Caption</caption>\n  <tr><th>Head</th><th>Head</th></tr>\n  <tr><td>Cell</td><td>Cell</td></tr>\n</table>',
    '<th> header cells, <td> cells; style="text-align:right" per cell',
    trigger: '<table',
  ),
  ComposeSnippet(
    'Tables',
    'Row',
    '<tr><td>\$|</td><td></td></tr>',
    'Table row',
    trigger: '<tr',
  ),
  ComposeSnippet(
    'Media',
    'Link',
    '<a href="https://\$|">\$SEL</a>',
    'Clickable link in the PDF',
    trigger: '<a',
  ),
  ComposeSnippet(
    'Media',
    'Image',
    '<img src="\$|image.png" width="60%">',
    'Local path (relative to the opened file) or data: URI; width in % or px',
    trigger: '<img',
  ),
  ComposeSnippet(
    'Media',
    'Figure with caption',
    '<figure>\n  <img src="\$|image.png" width="70%">\n  <figcaption>Caption</figcaption>\n</figure>',
    'Picture plus caption',
    trigger: '<figure',
  ),
  ComposeSnippet(
    'Maths',
    'Inline maths',
    r'\($|\)',
    r'TeX maths inside text: \( x^2 \)',
    trigger: r'\(',
  ),
  ComposeSnippet(
    'Maths',
    'Display maths',
    r'\[$|\]',
    r'Centred formula: \[ … \]',
    trigger: r'\[',
  ),
  ComposeSnippet(
    'Text',
    'Highlight',
    '<mark>\$SEL\$|</mark>',
    'Marked text',
    trigger: '<mark',
  ),
  ComposeSnippet(
    'Text',
    'Inline quote',
    '<q>\$SEL\$|</q>',
    '<q> inline quote, <abbr>, <cite>',
    trigger: '<q',
  ),
  ComposeSnippet(
    'Blocks',
    'Centred block',
    '<center>\n  \$|\n</center>',
    'Centres its contents',
    trigger: '<center',
  ),
  ComposeSnippet(
    'Blocks',
    'Address',
    '<address>\n  \$|Name<br>Street\n</address>',
    'Address block',
    trigger: '<address',
  ),
  ComposeSnippet(
    'Blocks',
    'Details',
    '<details>\n  <summary>\$|Summary</summary>\n  Content\n</details>',
    'Summary heading with content',
    trigger: '<details',
  ),
  ComposeSnippet(
    'Tables',
    'Header + body',
    '<table>\n  <thead><tr><th>\$|A</th><th>B</th></tr></thead>\n  <tbody><tr><td>1</td><td>2</td></tr></tbody>\n</table>',
    'Header row repeats on each page',
    trigger: '<thead',
  ),
  ..._math,
];

const _latex = <ComposeSnippet>[
  ComposeSnippet(
    'Document',
    'Article skeleton',
    '\\documentclass[11pt,a4paper]{article}\n\\usepackage{amsmath}\n\\usepackage{graphicx}\n\n\\title{\$|Title}\n\\author{Author}\n\\date{\\today}\n\n\\begin{document}\n\\maketitle\n\n\\end{document}\n',
    'documentclass options: 10pt/11pt/12pt, a4paper/letterpaper/a5paper',
    trigger: r'\documentclass',
  ),
  ComposeSnippet(
    'Document',
    'Title block',
    '\\maketitle',
    'Prints \\title, \\author and \\date',
    trigger: r'\maketitle',
  ),
  ComposeSnippet(
    'Document',
    'Table of contents',
    '\\tableofcontents',
    'Contents with page numbers',
    trigger: r'\tableofcontents',
  ),
  ComposeSnippet(
    'Document',
    'Abstract',
    '\\begin{abstract}\n\$|\n\\end{abstract}',
    'Summary paragraph',
    trigger: r'\begin{abstract}',
  ),
  ComposeSnippet(
    'Document',
    'New page',
    '\\newpage',
    'Also \\clearpage',
    trigger: r'\newpage',
  ),
  ComposeSnippet(
    'Document',
    'Own command',
    '\\newcommand{\\\$|name}{replacement}',
    '\\newcommand{\\R}{\\mathbb{R}}; with arguments: \\newcommand{\\pair}[2]{(#1,#2)}',
    trigger: r'\newcommand',
  ),
  ComposeSnippet(
    'Sections',
    'Section',
    '\\section{\$SEL\$|}',
    'Numbered 1, 2, 3; \\section*{…} unnumbered',
    trigger: r'\section',
  ),
  ComposeSnippet(
    'Sections',
    'Subsection',
    '\\subsection{\$SEL\$|}',
    'Numbered 1.1',
    trigger: r'\subsection',
  ),
  ComposeSnippet(
    'Sections',
    'Subsubsection',
    '\\subsubsection{\$SEL\$|}',
    'Numbered 1.1.1',
    trigger: r'\subsubsection',
  ),
  ComposeSnippet(
    'Sections',
    'Paragraph heading',
    '\\paragraph{\$SEL\$|}',
    'Small bold run-in heading',
    trigger: r'\paragraph',
  ),
  ComposeSnippet(
    'Sections',
    'Chapter',
    '\\chapter{\$SEL\$|}',
    'For books / reports',
    trigger: r'\chapter',
  ),
  ComposeSnippet(
    'Text',
    'Bold',
    '\\textbf{\$SEL\$|}',
    'Bold text',
    trigger: r'\textbf',
  ),
  ComposeSnippet(
    'Text',
    'Italic',
    '\\textit{\$SEL\$|}',
    'Italic text',
    trigger: r'\textit',
  ),
  ComposeSnippet(
    'Text',
    'Emphasis',
    '\\emph{\$SEL\$|}',
    'Emphasis (italic, or upright inside italic)',
    trigger: r'\emph',
  ),
  ComposeSnippet(
    'Text',
    'Underline',
    '\\underline{\$SEL\$|}',
    'Underlined text',
    trigger: r'\underline',
  ),
  ComposeSnippet(
    'Text',
    'Typewriter',
    '\\texttt{\$SEL\$|}',
    'Monospace text',
    trigger: r'\texttt',
  ),
  ComposeSnippet(
    'Text',
    'Small caps',
    '\\textsc{\$SEL\$|}',
    'Small capitals',
    trigger: r'\textsc',
  ),
  ComposeSnippet(
    'Text',
    'Colour',
    '\\textcolor{red}{\$SEL\$|}',
    'Names: red green blue orange purple gray … or \\color{blue} for the rest of a group',
    trigger: r'\textcolor',
  ),
  ComposeSnippet(
    'Text',
    'Sizes',
    '{\\large \$SEL\$|}',
    '\\tiny \\scriptsize \\footnotesize \\small \\normalsize \\large \\Large \\LARGE \\huge \\Huge',
    trigger: r'\large',
  ),
  ComposeSnippet(
    'Text',
    'Footnote',
    '\\footnote{\$|}',
    'Numbered note listed at the end',
    trigger: r'\footnote',
  ),
  ComposeSnippet(
    'Text',
    'Link',
    '\\href{https://\$|}{text}',
    'Clickable link; \\url{…} shows the address',
    trigger: r'\href',
  ),
  ComposeSnippet(
    'Text',
    'Line break',
    '\\\\',
    'New line; leave a blank line for a new paragraph',
    trigger: r'\\',
  ),
  ComposeSnippet(
    'Text',
    'Quotes and dashes',
    "``quoted'' -- en dash, --- em dash",
    'TeX typography; ~ is a non-breaking space',
  ),
  ComposeSnippet(
    'Text',
    'Special characters',
    r'\% \$ \& \# \_ \{ \}',
    'Escape reserved characters with a backslash',
  ),
  ComposeSnippet(
    'Text',
    'Today',
    '\\today',
    'Current date',
    trigger: r'\today',
  ),
  ComposeSnippet(
    'Lists',
    'Bulleted list',
    '\\begin{itemize}\n  \\item \$|\n  \\item \n\\end{itemize}',
    'Bullets; \\item[label] for a custom marker',
    trigger: r'\begin{itemize}',
  ),
  ComposeSnippet(
    'Lists',
    'Numbered list',
    '\\begin{enumerate}\n  \\item \$|\n  \\item \n\\end{enumerate}',
    '1. 2. 3. (nested: a. b. / i. ii.)',
    trigger: r'\begin{enumerate}',
  ),
  ComposeSnippet(
    'Lists',
    'Description list',
    '\\begin{description}\n  \\item[Term] \$|\n\\end{description}',
    'Bold terms with descriptions',
    trigger: r'\begin{description}',
  ),
  ComposeSnippet(
    'Lists',
    'Item',
    '\\item \$|',
    'One list entry',
    trigger: r'\item',
  ),
  ComposeSnippet(
    'Layout',
    'Centre',
    '\\begin{center}\n\$SEL\$|\n\\end{center}',
    'Centred block; flushleft / flushright too',
    trigger: r'\begin{center}',
  ),
  ComposeSnippet(
    'Layout',
    'Quote',
    '\\begin{quote}\n\$SEL\$|\n\\end{quote}',
    'Indented quotation (quotation, verse)',
    trigger: r'\begin{quote}',
  ),
  ComposeSnippet(
    'Layout',
    'Verbatim / code',
    '\\begin{verbatim}\n\$|\n\\end{verbatim}',
    'Code exactly as typed; lstlisting and minted{lang} work too',
    trigger: r'\begin{verbatim}',
  ),
  ComposeSnippet(
    'Layout',
    'Vertical space',
    '\\vspace{1em}',
    'Also \\smallskip \\medskip \\bigskip',
    trigger: r'\vspace',
  ),
  ComposeSnippet(
    'Layout',
    'Horizontal rule',
    '\\noindent\\rule{\\linewidth}{0.4pt}',
    'Full-width line',
    trigger: r'\rule',
  ),
  ComposeSnippet(
    'Layout',
    'No indent',
    '\\noindent ',
    'Start a paragraph flush left',
    trigger: r'\noindent',
  ),
  ComposeSnippet(
    'Theorems',
    'Theorem',
    '\\begin{theorem}\n\$|\n\\end{theorem}',
    'Also lemma, definition, corollary, remark, example',
    trigger: r'\begin{theorem}',
  ),
  ComposeSnippet(
    'Theorems',
    'Proof',
    '\\begin{proof}\n\$|\n\\end{proof}',
    'Ends with ∎',
    trigger: r'\begin{proof}',
  ),
  ComposeSnippet(
    'Floats',
    'Figure',
    '\\begin{figure}[h]\n  \\centering\n  \\includegraphics[width=0.7\\textwidth]{\$|image.png}\n  \\caption{Caption}\n  \\label{fig:name}\n\\end{figure}',
    'Picture with numbered caption; width=…\\textwidth or scale=…',
    trigger: r'\begin{figure}',
  ),
  ComposeSnippet(
    'Floats',
    'Image',
    '\\includegraphics[width=0.5\\textwidth]{\$|image.png}',
    'Path relative to the opened .tex file',
    trigger: r'\includegraphics',
  ),
  ComposeSnippet(
    'Floats',
    'Table',
    '\\begin{table}[h]\n  \\centering\n  \\begin{tabular}{|l|c|r|}\n    \\hline\n    A & B & C \\\\\n    \\hline\n    \$|1 & 2 & 3 \\\\\n    \\hline\n  \\end{tabular}\n  \\caption{Caption}\n\\end{table}',
    'Columns: l c r (p{3cm} for wrapping); & between cells, \\\\ ends a row, \\hline rules',
    trigger: r'\begin{table}',
  ),
  ComposeSnippet(
    'Floats',
    'Tabular',
    '\\begin{tabular}{ll}\n  \$|a & b \\\\\n  c & d \\\\\n\\end{tabular}',
    'Table without a float; booktabs \\toprule \\midrule \\bottomrule work',
    trigger: r'\begin{tabular}',
  ),
  ComposeSnippet(
    'Floats',
    'Caption',
    '\\caption{\$|}',
    'Numbered caption',
    trigger: r'\caption',
  ),
  ComposeSnippet(
    'References',
    'Label',
    '\\label{\$|}',
    'Name a section, equation, figure or table',
    trigger: r'\label',
  ),
  ComposeSnippet(
    'References',
    'Reference',
    '\\ref{\$|}',
    'Its number; \\eqref{…} adds brackets',
    trigger: r'\ref',
  ),
  ComposeSnippet(
    'References',
    'Citation',
    '\\cite{\$|}',
    'Shown as [key]',
    trigger: r'\cite',
  ),
  ComposeSnippet(
    'Maths',
    'Inline maths',
    r'$$|$',
    r'In a sentence: $x^2$ or \( x^2 \)',
    trigger: r'$',
  ),
  ComposeSnippet(
    'Maths',
    'Display maths',
    '\\[\n  \$|\n\\]',
    'Centred, unnumbered',
    trigger: r'\[',
  ),
  ComposeSnippet(
    'Maths',
    'Equation',
    '\\begin{equation}\n  \$|\n  \\label{eq:name}\n\\end{equation}',
    'Numbered; equation* for none',
    trigger: r'\begin{equation}',
  ),
  ComposeSnippet(
    'Maths',
    'Aligned equations',
    '\\begin{align}\n  a &= b + c \\\\\n  \$|d &= e\n\\end{align}',
    '& aligns, \\\\ breaks the line; align* unnumbered, \\nonumber per line',
    trigger: r'\begin{align}',
  ),
  ComposeSnippet(
    'Maths',
    'Gathered equations',
    '\\begin{gather}\n  \$|\n\\end{gather}',
    'Centred lines, numbered',
    trigger: r'\begin{gather}',
  ),
  ComposeSnippet(
    'Text',
    'Superscript text',
    '\\textsuperscript{\$|}',
    'Raised text: 1\\textsuperscript{st}',
    trigger: r'\textsuperscript',
  ),
  ComposeSnippet(
    'Text',
    'Sans-serif / roman',
    '\\textsf{\$SEL\$|}',
    '\\textsf sans-serif, \\textrm roman, \\textup upright',
    trigger: r'\textsf',
  ),
  ComposeSnippet(
    'Text',
    'Non-breaking space',
    'Fig.~\\ref{\$|}',
    '~ keeps two words on one line',
  ),
  ComposeSnippet(
    'Text',
    'Horizontal fill',
    '\\hfill',
    'Push what follows to the right edge',
    trigger: r'\hfill',
  ),
  ComposeSnippet(
    'Text',
    'Accents',
    "\\'e \\`a \\^o \\\"u \\~n \\c{c}",
    'é à ô ü ñ ç',
  ),
  ComposeSnippet(
    'Layout',
    'Minipage',
    '\\begin{minipage}{0.48\\textwidth}\n\$|\n\\end{minipage}',
    'A box of text inside the page',
    trigger: r'\begin{minipage}',
  ),
  ComposeSnippet(
    'Layout',
    'Flush right',
    '\\begin{flushright}\n\$|\n\\end{flushright}',
    'Right-aligned block (flushleft for left)',
    trigger: r'\begin{flushright}',
  ),
  ComposeSnippet(
    'Theorems',
    'Definition',
    '\\begin{definition}\n\$|\n\\end{definition}',
    'Bold "Definition." heading',
    trigger: r'\begin{definition}',
  ),
  ComposeSnippet(
    'Theorems',
    'Lemma',
    '\\begin{lemma}\n\$|\n\\end{lemma}',
    'Bold "Lemma." heading',
    trigger: r'\begin{lemma}',
  ),
  ComposeSnippet(
    'Floats',
    'Booktabs table',
    '\\begin{tabular}{lcr}\n  \\toprule\n  A & B & C \\\\\n  \\midrule\n  \$|1 & 2 & 3 \\\\\n  \\bottomrule\n\\end{tabular}',
    'Professional rules, no vertical lines',
    trigger: r'\toprule',
  ),
  ComposeSnippet(
    'Floats',
    'Spanning cell',
    '\\multicolumn{2}{c}{\$|}',
    'One cell across several columns',
    trigger: r'\multicolumn',
  ),
  ComposeSnippet(
    'Maths',
    'Bracket matrix',
    '\\begin{bmatrix} \$|a & b \\\\ c & d \\end{bmatrix}',
    'Square-bracket matrix',
    trigger: r'\begin{bmatrix}',
  ),
  ComposeSnippet(
    'Maths',
    'Determinant',
    '\\begin{vmatrix} \$|a & b \\\\ c & d \\end{vmatrix}',
    'Vertical bars',
    trigger: r'\begin{vmatrix}',
  ),
  ComposeSnippet(
    'Maths',
    'Aligned (inline block)',
    '\\begin{aligned} \$|a &= b \\\\ c &= d \\end{aligned}',
    'Alignment inside display maths',
    trigger: r'\begin{aligned}',
  ),
  ComposeSnippet(
    'Maths',
    'Operator name',
    '\\operatorname{\$|}',
    'Custom upright function (rank, tr)',
    trigger: r'\operatorname',
  ),
  ComposeSnippet(
    'Maths',
    'Over / under line',
    '\\overline{\$|}',
    '\\overline \\underline \\widehat \\widetilde',
    trigger: r'\overline',
  ),
  ComposeSnippet(
    'Maths',
    'Stacked relation',
    '\\stackrel{\\text{def}}{=}',
    'Symbol above a relation',
    trigger: r'\stackrel',
  ),
  ComposeSnippet(
    'Maths',
    'Calligraphic / fraktur',
    '\\mathcal{\$|}',
    '\\mathcal{L} \\mathfrak{g} \\mathsf{X}',
    trigger: r'\mathcal',
  ),
  ComposeSnippet(
    'Maths',
    'Not / negation',
    '\\not\\in',
    '\\not= \\nleq \\nsubseteq',
    trigger: r'\not',
  ),
  ComposeSnippet(
    'Maths',
    'Boxed result',
    '\\boxed{\$|}',
    'Frame an answer',
    trigger: r'\boxed',
  ),
  ..._math,
];
