import 'dart:io';

import 'package:document_studio/core/desktop/desktop_engine_resolver.dart';
import 'package:document_studio/infrastructure/pdf/pdfa/srgb_icc.dart';
import 'package:path/path.dart' as p;

/// Result of [convertToPdfA].
class PdfAResult {
  const PdfAResult.ok(this.outputPath) : error = null;
  const PdfAResult.failed(this.error) : outputPath = null;

  final String? outputPath;
  final String? error;
  bool get ok => outputPath != null;
}

/// PDF/A conformance levels offered.
enum PdfALevel {
  a1b(1, 'PDF/A-1b'),
  a2b(2, 'PDF/A-2b'),
  a3b(3, 'PDF/A-3b');

  const PdfALevel(this.part, this.label);
  final int part;
  final String label;
}

/// Converts [inputPath] to PDF/A with Ghostscript: every font is embedded
/// (missing ones substituted), colours are tagged with an sRGB output intent
/// (profile generated by [buildSrgbIccProfile]), XMP identification is
/// written, and forbidden features (JavaScript, encryption) are dropped.
///
/// The password, if any, goes through a private argument file, never argv.
Future<PdfAResult> convertToPdfA({
  required String inputPath,
  required String outputPath,
  PdfALevel level = PdfALevel.a2b,
  String? password,
  String? title,
}) async {
  final gs = await desktopEngineResolver.resolveGhostscript();
  if (gs == null) {
    return const PdfAResult.failed(
      'PDF/A conversion needs Ghostscript. Install it from ghostscript.com '
      '(Windows) or your package manager (e.g. "sudo apt install '
      'ghostscript"), then try again.',
    );
  }
  final dir = await Directory.systemTemp.createTemp('ds_pdfa_');
  try {
    if (!Platform.isWindows) {
      await Process.run('chmod', ['700', dir.path]);
    }
    final icc = File(p.join(dir.path, 'srgb.icc'));
    await icc.writeAsBytes(buildSrgbIccProfile(), flush: true);
    final def = File(p.join(dir.path, 'pdfa_def.ps'));
    await def.writeAsString(_pdfaDef(icc.path, title));
    final args = <String>[
      '-dPDFA=${level.part}',
      '-dBATCH',
      '-dNOPAUSE',
      '-dNOOUTERSAVE',
      '-dQUIET',
      '-dSAFER',
      '-dPDFACompatibilityPolicy=1',
      '-sColorConversionStrategy=RGB',
      '-sProcessColorModel=DeviceRGB',
      '-dEmbedAllFonts=true',
      '-dSubsetFonts=true',
      '-sDEVICE=pdfwrite',
      '--permit-file-read=${dir.path}${Platform.pathSeparator}',
      '-sOutputFile=$outputPath',
      if (password != null && password.isNotEmpty) '-sPDFPassword=$password',
      def.path,
      inputPath,
    ];
    // Ghostscript reads @file arguments; keeps the password out of argv.
    final argFile = File(p.join(dir.path, 'args'));
    if (args.any((a) => a.contains('"') || a.contains('\n'))) {
      return const PdfAResult.failed(
        'The file name or password contains a quote or line break that '
        'Ghostscript cannot accept. Rename the file or remove the password '
        'first.',
      );
    }
    await argFile.writeAsString(
      '${args.map(_quote).join('\n')}\n',
      flush: true,
    );
    if (!Platform.isWindows) {
      await Process.run('chmod', ['600', argFile.path]);
    }
    final r = await Process.run(gs, ['@${argFile.path}']);
    final out = File(outputPath);
    if (r.exitCode != 0 || !await out.exists() || await out.length() == 0) {
      final err = '${r.stderr}'.trim();
      return PdfAResult.failed(
        err.isEmpty ? 'Ghostscript could not convert this file.' : err,
      );
    }
    return PdfAResult.ok(outputPath);
  } catch (e) {
    return PdfAResult.failed('$e');
  } finally {
    try {
      await dir.delete(recursive: true);
    } catch (_) {}
  }
}

String _quote(String a) => '"$a"';

String _ps(String s) =>
    s.replaceAll(r'\', r'\\').replaceAll('(', r'\(').replaceAll(')', r'\)');

String _pdfaDef(String iccPath, String? title) =>
    '''
%!
/ICCProfile (${_ps(iccPath.replaceAll(r'\', '/'))}) def
${title == null || title.isEmpty ? '' : '[ /Title (${_ps(title)}) /DOCINFO pdfmark'}
[/_objdef {icc_PDFA} /type /stream /OBJ pdfmark
[{icc_PDFA} << /N 3 >> /PUT pdfmark
[{icc_PDFA} ICCProfile (r) file /PUT pdfmark
[/_objdef {OutputIntent_PDFA} /type /dict /OBJ pdfmark
[{OutputIntent_PDFA} <<
  /Type /OutputIntent
  /S /GTS_PDFA1
  /DestOutputProfile {icc_PDFA}
  /OutputConditionIdentifier (sRGB)
  /Info (sRGB IEC61966-2.1)
>> /PUT pdfmark
[{Catalog} << /OutputIntents [ {OutputIntent_PDFA} ] >> /PUT pdfmark
''';
