/// Tools that can run in the viewer embedded panel (T6).
enum ViewerToolId {
  compress,
  protect,
  unlock,
  metadata,
  removeMetadata,
  watermark,
  pageNumbers,
  headersFooters,
  crop,
  resize,
  exportImages,
  exportJpg,
  exportPng,
  split,
  extract,
  deletePages,
  rotate,
  duplicate,
  reverse,
  insertBlank,
  workspaceMerge,
  workspaceReorder,
  workspaceMoveBetween,
  workspaceInsert,
  workspaceReplace,
  redact,
  fillForm,
  officeConvert,
  ink,
  searchablePdf,
  blockedSearchablePdf,
  blockedOcrImage,
  placeImage,
  visualSign,
  insertScan,
  ocrImage,
  batch,
  markupBurn,
  compare,
  editText,
  addLink,
  accessibilityTags,
}

extension ViewerToolIdLabels on ViewerToolId {
  String get panelTitle => switch (this) {
    ViewerToolId.compress => 'Compress',
    ViewerToolId.protect => 'Encrypt',
    ViewerToolId.unlock => 'Decrypt',
    ViewerToolId.metadata => 'Edit metadata',
    ViewerToolId.removeMetadata => 'Remove metadata',
    ViewerToolId.watermark => 'Watermark',
    ViewerToolId.pageNumbers => 'Page numbers',
    ViewerToolId.headersFooters => 'Header and footer',
    ViewerToolId.crop => 'Crop',
    ViewerToolId.resize => 'Resize pages',
    ViewerToolId.exportImages => 'Export to images',
    ViewerToolId.exportJpg => 'Export to JPG',
    ViewerToolId.exportPng => 'Export to PNG',
    ViewerToolId.split => 'Split',
    ViewerToolId.extract => 'Extract pages',
    ViewerToolId.deletePages => 'Delete pages',
    ViewerToolId.rotate => 'Rotate',
    ViewerToolId.duplicate => 'Duplicate pages',
    ViewerToolId.reverse => 'Reverse order',
    ViewerToolId.insertBlank => 'Add blank page',
    ViewerToolId.workspaceMerge => 'Merge',
    ViewerToolId.workspaceReorder => 'Organize',
    ViewerToolId.workspaceMoveBetween => 'Move between documents',
    ViewerToolId.workspaceInsert => 'Insert pages',
    ViewerToolId.workspaceReplace => 'Replace pages',
    ViewerToolId.redact => 'Redact',
    ViewerToolId.fillForm => 'Fill PDF form',
    ViewerToolId.officeConvert => 'Office convert',
    ViewerToolId.ink => 'Draw ink',
    ViewerToolId.searchablePdf => 'Searchable PDF',
    ViewerToolId.blockedSearchablePdf => 'Searchable PDF',
    ViewerToolId.blockedOcrImage => 'Image OCR',
    ViewerToolId.placeImage => 'Place image',
    ViewerToolId.visualSign => 'Sign PDF',
    ViewerToolId.insertScan => 'Insert scan',
    ViewerToolId.ocrImage => 'Image OCR',
    ViewerToolId.batch => 'Batch',
    ViewerToolId.markupBurn => 'Markup',
    ViewerToolId.compare => 'Compare PDFs',
    ViewerToolId.editText => 'Edit text',
    ViewerToolId.addLink => 'Add link',
    ViewerToolId.accessibilityTags => 'Accessibility',
  };

  bool get isBlockedCapability => switch (this) {
    ViewerToolId.blockedSearchablePdf || ViewerToolId.blockedOcrImage => true,
    _ => false,
  };

  bool get isWorkspaceHandoff => switch (this) {
    ViewerToolId.workspaceMoveBetween ||
    ViewerToolId.workspaceInsert ||
    ViewerToolId.workspaceReplace => true,
    _ => false,
  };
}

/// Maps standalone tool route paths (Home / Tools hub) to embedded viewer panels.
ViewerToolId? viewerToolIdFromToolRoutePath(String path) {
  final normalized = path.split('?').first;
  return switch (normalized) {
    '/compress' => ViewerToolId.compress,
    '/protect' => ViewerToolId.protect,
    '/unlock' => ViewerToolId.unlock,
    '/metadata' => ViewerToolId.metadata,
    '/remove-metadata' => ViewerToolId.removeMetadata,
    '/watermark' => ViewerToolId.watermark,
    '/page-numbers' => ViewerToolId.pageNumbers,
    '/headers-footers' => ViewerToolId.headersFooters,
    '/pdf-to-images' => ViewerToolId.exportImages,
    '/office-convert' => ViewerToolId.officeConvert,
    '/ocr/image' => ViewerToolId.ocrImage,
    '/organize/crop' => ViewerToolId.crop,
    '/organize/resize' => ViewerToolId.resize,
    '/organize/merge' => ViewerToolId.workspaceMerge,
    '/organize/split' => ViewerToolId.split,
    '/organize/extract' => ViewerToolId.extract,
    '/organize/delete' => ViewerToolId.deletePages,
    '/organize/rotate' => ViewerToolId.rotate,
    '/organize/duplicate' => ViewerToolId.duplicate,
    '/organize/reverse' => ViewerToolId.reverse,
    '/organize/blank-page' => ViewerToolId.insertBlank,
    '/redact' => ViewerToolId.redact,
    '/forms/fill' => ViewerToolId.fillForm,
    '/sign/visual' => ViewerToolId.visualSign,
    '/ocr/searchable-pdf' => ViewerToolId.searchablePdf,
    '/batch' => ViewerToolId.batch,
    _ => null,
  };
}

/// Maps Acrobat **All tools** rail / action ids.
ViewerToolId? viewerToolIdFromAcrobatToolId(String toolId) => switch (toolId) {
  'compress' => ViewerToolId.compress,
  'protect' => ViewerToolId.protect,
  'unlock' => ViewerToolId.unlock,
  'metadata' => ViewerToolId.metadata,
  'remove_metadata' => ViewerToolId.removeMetadata,
  'watermark' => ViewerToolId.watermark,
  'page_numbers' => ViewerToolId.pageNumbers,
  'headers_footers' => ViewerToolId.headersFooters,
  'export_images' => ViewerToolId.exportImages,
  'export_jpg' => ViewerToolId.exportJpg,
  'export_png' => ViewerToolId.exportPng,
  'organize_crop' => ViewerToolId.crop,
  'organize_resize' => ViewerToolId.resize,
  'organize_split' => ViewerToolId.split,
  'organize_extract' => ViewerToolId.extract,
  'organize_delete' => ViewerToolId.deletePages,
  'organize_rotate' => ViewerToolId.rotate,
  'organize_duplicate' => ViewerToolId.duplicate,
  'organize_reverse' => ViewerToolId.reverse,
  'organize_blank' => ViewerToolId.insertBlank,
  'organize_merge' => ViewerToolId.workspaceMerge,
  'organize_reorder' => ViewerToolId.workspaceReorder,
  'organize_move_between' => ViewerToolId.workspaceMoveBetween,
  'organize_insert' => ViewerToolId.workspaceInsert,
  'organize_replace' => ViewerToolId.workspaceReplace,
  'redact' => ViewerToolId.redact,
  'fill_form' => ViewerToolId.fillForm,
  'office_convert' => ViewerToolId.officeConvert,
  'ink' => ViewerToolId.ink,
  'draw' => ViewerToolId.ink,
  'ocr_searchable_pdf' => ViewerToolId.searchablePdf,
  'ocr_image' => ViewerToolId.ocrImage,
  'place_image' => ViewerToolId.placeImage,
  'visual_sign' => ViewerToolId.visualSign,
  'insert_scan' => ViewerToolId.insertScan,
  'batch' => ViewerToolId.batch,
  'markup_burn' => ViewerToolId.markupBurn,
  'compare' => ViewerToolId.compare,
  'edit_text' => ViewerToolId.editText,
  'add_text' => ViewerToolId.editText,
  'add_link' => ViewerToolId.addLink,
  'crop' => ViewerToolId.crop,
  'office_to_pdf' => ViewerToolId.officeConvert,
  'accessibility_tags' => ViewerToolId.accessibilityTags,
  _ => null,
};
