#!/bin/sh
# Remove untracked engine trees (LibreOffice version dirs, user drops) after dpkg
# deletes only files listed in the package manifest.
set -e

APP_DIR=/usr/lib/document-studio
DESKTOP=/usr/share/applications/com.documentstudio.document_studio.desktop
LAUNCHER=/usr/bin/document_studio

case "$1" in
  remove|purge)
    rm -rf "$APP_DIR"
    rm -f "$LAUNCHER" "$DESKTOP"
    ;;
  upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;
esac

exit 0
